# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0340840ad2e67263682443d5d13fc5da1e0bd7b9a914c89f09dfacb001d7edbdc4cdbccedfde7628b4c4d62be95a0fac06412b11491bacb849793f5cf90b2932

test:
  secret_key_base: 0fd4d7e080d53d1791e52d902ccdf7d34529a0925591cc191ae2eebf4c9dd510c74d469d7964de52cf411382de2423126560c005e3a4a53f7bb79b462ce412a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
